# Generated by Django 4.1.3 on 2023-11-15 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_answer_likes_remove_question_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlike',
            name='answer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_likes', to='app.answer'),
        ),
    ]
