# Generated by Django 4.1.3 on 2023-11-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_answerlike_answer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
